### ISSUE TITLE
Any plans on expanding this to other completers?

### ISSUE THREAD

**Issue by pope** [LuckyGeck/YcmdCompletion#1]
Do you have plans on expanding this to support other languages that YCMD supports, like Objective-C and C#? If not, would you be open to patches for that?

**Comment by LuckyGeck** [comment]
I'm quite busy now, so probably will not have time for supporting other languages. But it's not so difficult (just look throught examples at ycmd's github), so you can do it if you want.

Sure, any patches \ pull-requests are welcome)
