### ISSUE TITLE
[Ycmd][Notify] Error ''

### ISSUE THREAD

**Issue by begend** [LuckyGeck/YcmdCompletion#11]
hi, here is my conf:
{
    "HMAC": "7D/5FfQLFWmNK97H9yNTfw==",
    //"ycmd_port": 8080,
    //"ycmd_server": "http://127.0.0.1",
    "ycmd_path":"~/bin/ycmd",
    "python_path": "/usr/bin/python",
    //"use_auto":true,
    "use_auto_start_localserver":1
}

but, err in console:
[Ycmd][Notify] Error ''

thanks.

**Comment by LuckyGeck** [comment]
Hi! 
Feature about autostart is currently in dev channel of this plugin. If you have installed plugin from Command Palette of sublime, you have source code of stable branch, that has no support for this feature.

You can try dev branch by cloning plugin's repo into your sublime packages folder.

**Comment by begend** [comment]
thanks a lot

**Comment by LuckyGeck** [comment]
Autostart feature is finally released. You can update your plugin version in SublimeText.
