### ISSUE TITLE
Win32 - ycmd_path searched in system installation folder, not plugin folder

### ISSUE THREAD

**Issue by nyanpasu64** [LuckyGeck/YcmdCompletion#15]
I'm running Sublime 32 on Win64. I believe this bug happens on Sublime 64 as well.

I have this plugin installed in "installed packages" or extracted to "packages" in my user AppData folder.

get_ycmd_path() calls `settings.get('ycmd_path', os.path.join(get_plugin_path(), 'server'))`. This fetches `ycmd_path` from the default settings, defaulting to the user-local `Packages/C++YouCompleteMe`.

However, the default `ycmd_path` is a relative path, and `os.getcwd()` defaults to `Program Files` (Sublime install location), causing it to look for ycmd in the built-in plugin folder, rather than the user-plugin folder.

I'm not too familiar, but maybe you should `os.chdir(os.path.join(sublime.packages_path(), '..'))`. Are plugins supposed to change the OS directory?

Do I have another plugin mangling the current directory?

**Comment by LuckyGeck** [comment]
Hi!

I'm not sure if you are talking about my plugin - mine is named `YcmdCompletion`, not `C++YouCompleteMe`.
And my plugin doesn't have `get_ycmd_path()` call either. It gets settings via `sublime.load_settings(SETTINGS_NAME)` call.

**Comment by nyanpasu64** [comment]
this is the second erroneous issue report I made.

ycm is confusing.
