### ISSUE TITLE
Sublime could not find default_settings.json

### ISSUE THREAD

**Issue by sanwuwy** [LuckyGeck/YcmdCompletion#16]
I have completed Building YCMD instructions, and it can work well in VIM.
But when I use it in Sublime Text3, the console shows that:
- [Ycmd] Plugin loaded with autostart. Starting Ycmd.
- Traceback (most recent call last):
-   File "/opt/sublime_text/sublime_plugin.py", line 158, in on_api_ready
-     m.plugin_loaded()
-   File "/home/ts/.config/sublime-text-3/Packages/YcmdCompletion/Completion.py", line 74, in plugin_loaded
-     start_server(settings)
-   File "/home/ts/.config/sublime-text-3/Packages/YcmdCompletion/Completion.py", line 48, in start_server
-     default_settings_path)
-   File "/home/ts/.config/sublime-text-3/Packages/YcmdCompletion/ycmd/http_client.py", line 40, in StartYcmdAndReturnHandle
-     prepared_options = json.load(open(default_settings_path))
- FileNotFoundError: [Errno 2] No such file or directory: '~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/default_settings.json'

But I can find this default file in this path, and below is its content:
{
-   "filepath_completion_use_working_dir": 0,
-   "auto_trigger": 1,
-   "min_num_of_chars_for_completion": 2,
-   "min_num_identifier_candidate_chars": 0,
-   "semantic_triggers": {},
-   "filetype_specific_completion_to_disable": {
-     "gitcommit": 1
-   },
-   "seed_identifiers_with_syntax": 0,
-   "collect_identifiers_from_comments_and_strings": 0,
-   "collect_identifiers_from_tags_files": 0,
-   "max_num_identifier_candidates": 10,
-   "extra_conf_globlist": [],
-   "global_ycm_extra_conf": "~/.ycm_extra_conf.py",
-   "confirm_extra_conf": 1,
-   "complete_in_comments": 0,
-   "complete_in_strings": 1,
-   "max_diagnostics_to_display": 30,
-   "filetype_whitelist": {
-     "*": 1
-   },
-   "filetype_blacklist": {
-     "tagbar": 1,
-     "qf": 1,
-     "notes": 1,
-     "markdown": 1,
-     "unite": 1,
-     "text": 1,
-     "vimwiki": 1,
-     "pandoc": 1,
-     "infolog": 1,
-     "mail": 1
-   },
-   "auto_start_csharp_server": 1,
-   "auto_stop_csharp_server": 1,
-   "use_ultisnips_completer": 1,
-   "csharp_server_port": 0,
-   "hmac_secret": "UN+YrRI5GUXeMOqOPHWxUw==",
-   "server_keep_logfiles": 0,
-   "gocode_binary_path": "",
-   "rust_src_path": "",
-   "racerd_binary_path": ""
  }

Please help to watch what is it wrong, thanks!

**Comment by LuckyGeck** [comment]
Hi!
Maybe try replacing ~/.vim path with absolute path (e.g. /home/ts/.vim).

**Comment by LuckyGeck** [comment]
@sanwuwy, did it help?

**Comment by LuckyGeck** [comment]
Closing issue for now. If problem isn't solved yet, just reopen this issue.
