### ISSUE TITLE
It won't kill python automatically when ST3 closed

### ISSUE THREAD

**Issue by meritozh** [LuckyGeck/YcmdCompletion#18]
Every time, i must kill it manually.

BTW, how to set analyze to ignore `unused variable`? And how to inhibit the native ST completion which will disturb the completion list from `ycmd` server

**Comment by LuckyGeck** [comment]
Hi!
If you mean python subprocess for ycmd server - it should be killed, when plugin is unloaded.
In any case, ycmd server has a parameter, that sets max idle time, after which server will shutdown itself automatically.

To ignore warnings about unused variables and other language-specific stuff, you should mute specific warning via compiler flags. These flags can be passed to clang by settings them in your `.ycm_extra_conf.py` 

Plugin already inhibits native ST completions, but only when results are ready. So while ycmd hasn't replied to a completion request yet, you will see native completion.
This behavior can be changed via patching the plugin.

**Comment by meritozh** [comment]
Thanks, i want it can inhibits native ST completions when ycmd running. Because native completion will work when typing `#include <{cursor}>` and `std:{cursor}`

**Comment by LuckyGeck** [comment]
Created another issue for this feature. Current issue is solved.
