### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by Gronis** [LuckyGeck/YcmdCompletion#20]
EDIT: This actually works for me now, but I got another problem (See further down)

Hi, I'm trying to get this plugin to work with ycmd, but there seems to a problem with the HMAC.

I have the HMAC set in the plugin preferences like this:

```
{
    "HMAC": "MVOwK7eqbxE258q5VmX0Fg==",
    "use_auto_start_localserver": 1,
    "ycmd_path": "/Users/robin/git/ycmd/ycmd"
}
```

And in the settings for ycmd like this

```
{
  ...
  "global_ycm_extra_conf": "/Users/robin/git/ycmd/ycmd/ycm_extra_conf.py",
  "hmac_secret": "MVOwK7eqbxE258q5VmX0Fg==",
  ...
}
```

However, when YcmdCompletion tries to communicate with ycmd, I receive this error in the sublime console: 

```
[YCMD] #### START COMPLETION ####
[Ycmd][Notify] /Users/robin/Downloads/untitled.cpp
[Ycmd][Notify] Error HTTP Error 401: Unauthorized
[Ycmd][Completion] for /Users/robin/Downloads/untitled.cpp:29:5
[Ycmd][Completion] Error HTTP Error 401: Unauthorized
```

And from the terminal I started ycmd:

```
python2.7 ycmd --options_file=default_settings.json --port 52656
serving on http://127.0.0.1:52656
2016-03-23 21:47:40,602 - INFO - Dropping request with bad HMAC.
2016-03-23 21:47:40,623 - INFO - Dropping request with bad HMAC.
```

Why is this? I have the same HMAC in both of the files. Is there something I missed?

**Comment by Gronis** [comment]
Also, I might also add that the autostarted ycmd instance crashes (there is something about my python version that's wrong) So I run it from the terminal instead with the same port as the crashed ycmd instance.

**Comment by Gronis** [comment]
Ok, a little embarrassing, but fixing my python version by creating a new soft link for /usr/bin/python actually solved the HMAC problem (Now using the autostarted ycmd server). However, now I get these error messages in the sublime console:

```
[YCMD] #### START COMPLETION ####
[Ycmd][Notify] /Users/robin/Downloads/untitled.cpp
[Ycmd][Notify] Error 'NoneType' object has no attribute 'SendEventNotification'
[Ycmd][Completion] for /Users/robin/Downloads/untitled.cpp:29:5
[Ycmd][Completion] Error 'NoneType' object has no attribute 'SendCodeCompletionRequest'
```

Any idea how to solve this?

**Comment by LuckyGeck** [comment]
Hi! Use "python_binary_path" param in plugin's settings.
Like this line in sample configs: https://github.com/LuckyGeck/YcmdCompletion/blob/master/YcmdCompletion.sublime-settings#L48
