### ISSUE TITLE
I get the error notification, but faill to get completions.

### ISSUE THREAD

**Issue by kaushikcfd** [LuckyGeck/YcmdCompletion#24]
Hello,
As you could see in the screen-shot below, `Sublime Text 3` is able to to do error highlighting but does not give any completions. The same `YCMD` server has been used with `Atom` and the same mentioned `.ycm_extra_conf.py` and it produces excellent results. I think I am missing something. It would be really great if someone could point out. 
Thank you. 
![screenshot from 2016-06-04 12 49 46](https://cloud.githubusercontent.com/assets/15399010/15798350/13b1bc0a-2a53-11e6-9287-5f7eca9d6142.png)

**Comment by LuckyGeck** [comment]
Hi! If you getting error messages, then autocompletion should work as well, because it work using the same code and settings. You can try to debug this situation by checking, whether there are any messages in Sublime Text console.

**Comment by kaushikcfd** [comment]
Thanks for the reply. I just checked the console the following error popped up.
<pre><code>
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 162, in on_api_ready
    m.plugin_loaded()
  File "/home/kaushikcfd/.config/sublime-text-3/Packages/YcmdCompletion/Completion.py", line 77, in plugin_loaded
    start_server(settings)
  File "/home/kaushikcfd/.config/sublime-text-3/Packages/YcmdCompletion/Completion.py", line 51, in start_server
    default_settings_path)
  File "/home/kaushikcfd/.config/sublime-text-3/Packages/YcmdCompletion/ycmd/http_client.py", line 44, in StartYcmdAndReturnHandle
    server_port = GetUnusedLocalhostPort()
  File "/home/kaushikcfd/.config/sublime-text-3/Packages/YcmdCompletion/ycmd/http_client.py", line 216, in GetUnusedLocalhostPort
    sock.bind(('', 0))
LookupError: unknown encoding: idna
</pre></code>
I don't get it. But would be great if you could suggest me to try something.

**Comment by LuckyGeck** [comment]
Please, provide me with following info:
- Your OS Family\Version
- Sublime Text version
- Your configs (plugin's config and other files that you have created for this plugin to make it work).

**Comment by kaushikcfd** [comment]
Sure. Here you go:
- OS: Ubuntu 14.04
- Sublime Text 3 (Re-installed in today)
- I have currently installed 3 packages:
1. Package Control
2. YcmdCompletion
3. SublimeLinter
- Here goes my Plugin Settings:
  **Default Settings**
  
  <pre><code>
  {
  /* =====       YCMD MANUAL START MODE       =====*/
  /* [1] Server URL, where your YCMD server is started */
  "ycmd_server": "http://127.0.0.1",
  /* [2] Server's port*/
  "ycmd_port": 8080,
  /* [3] You can set a rule for filepath modification */
  /*
    YCMD server will be asked to work with cur_file_path.replace(from, to)
    It can be usefull if using remote ycmd server and remote project's
    location has different prefix from local's
  */
  /* [!UNCOMMENT THIS, IF NEEDED!] */
  // "ycmd_filepath_replace": {
  //   "from": "/Users/username/",
  //   "to": "/place/home/username/",
  // },
  /* [3] HMAC is needed to securely connect to YCMD server */
  /*
    You should have the same HMAC settings in sublime text and in ycmd settings.
    To generate new HMAC you can use [Command Palette] -> "Ycmd: Create HMAC keys"
  */
  "HMAC": "Wqm9l1IEE5KD7AoxS3+HwA==",
  /* =====       YCMD AUTO START MODE       =====*/
  /*
    If you want this plugin to automatically launch local ycmd-server:
    a) Set "use_auto_start_localserver" to 1
    b) Specify the path to your ycmd installation.
    Ex:
  */
  "use_auto_start_localserver": 1,
  "ycmd_path": "/home/kaushikcfd/MyStuff/ClonedRepos/ycmd/ycmd",
  /*
    By default, plugin starts ycmd server with it's default settings (from ycmd_path + '/default_settings.json')
    If you want to override path to ycmd settings, uncomment this:
  */
  "default_settings_path":"/home/kaushikcfd/MyStuff/ClonedRepos/ycmd/ycmd/default_settings.json",
  /*
    If you want to override path to python binary, that will be used to run ycmd server
    and other tools, uncomment this:
  */
  "python_binary_path": "/usr/local/bin/python2",
  /*
    The languages you wish to use ycmd for.
    Supported: cpp, rust, python, go
    The following languages may also work, but are untested with this plugin:
    c, erlang, java, d, lua,
    ocaml, js, perl, objc,
    cs, php, ruby, rust
    These languages may also work if the corresponding Sublime
    syntax plugin is installed:
    vb, typescript, elixir
    Be sure to run the "Reload language list from settings" command
    after editing this setting
  */
  "languages": ["cpp", "python"],
  }
  </code></pre>
  
  **User Settings**
  
  <pre><code>
  {
  "HMAC": "Wqm9l1IEE5KD7AoxS3+HwA=="
  }
  </code></pre>
  
  Thanks once again for looking into it.

**Comment by LuckyGeck** [comment]
As I've previously mentioned, if you have seen syntax errors highlighted by
the plugin, your server started successfully and your configs worked well.
So, the error you have posted may have no relation to the working
configuration.
Just try to trigger completion action by pressing ctrl+space or typing a
dot after some class object.

2016-06-04 15:04 GMT+03:00 Kaushik Kulkarni notifications@github.com:

> Sure. Here you go:
> - OS: Ubuntu 14.04
> - ## Sublime Text 3 (Re-installed in today)
>   
>   I have currently installed 3 packages:
> 1. Package Control
> 2. YcmdCompletion
>    3.
>    
>    SublimeLinter
>    
>    ## 
>    
>    Here goes my Plugin Settings:
>    _Default Settings_
>    
>    {
>    /\* =====       YCMD MANUAL START MODE       =====_/
>    /_ [1] Server URL, where your YCMD server is started _/
>    "ycmd_server": "http://127.0.0.1",
>    /_ [2] Server's port*/
>    "ycmd_port": 8080,
>    
>    /\* [3] You can set a rule for filepath modification _/
>    /_
>     YCMD server will be asked to work with cur_file_path.replace(from, to)
>     It can be usefull if using remote ycmd server and remote project's
>     location has different prefix from local's
>    */
>    
>    /\* [!UNCOMMENT THIS, IF NEEDED!] */
>    // "ycmd_filepath_replace": {
>    //   "from": "/Users/username/",
>    //   "to": "/place/home/username/",
>    // },
>    
>    /\* [3] HMAC is needed to securely connect to YCMD server _/
>    /_
>     You should have the same HMAC settings in sublime text and in ycmd settings.
>     To generate new HMAC you can use [Command Palette] -> "Ycmd: Create HMAC keys"
>    */
>    "HMAC": "Wqm9l1IEE5KD7AoxS3+HwA==",
>    
>    /\* =====       YCMD AUTO START MODE       =====_/
>    /_
>     If you want this plugin to automatically launch local ycmd-server:
>     a) Set "use_auto_start_localserver" to 1
>     b) Specify the path to your ycmd installation.
>     Ex:
>    */
>    "use_auto_start_localserver": 1,
>    "ycmd_path": "/home/kaushikcfd/MyStuff/ClonedRepos/ycmd/ycmd",
>    
>    /*
>     By default, plugin starts ycmd server with it's default settings (from ycmd_path + '/default_settings.json')
>     If you want to override path to ycmd settings, uncomment this:
>    _/
>    "default_settings_path":"/home/kaushikcfd/MyStuff/ClonedRepos/ycmd/ycmd/default_settings.json",
>    /_
>     If you want to override path to python binary, that will be used to run ycmd server
>     and other tools, uncomment this:
>    */
>    "python_binary_path": "/usr/local/bin/python2",
>    
>    /*
>     The languages you wish to use ycmd for.
>     Supported: cpp, rust, python, go
>    
>     The following languages may also work, but are untested with this plugin:
>     c, erlang, java, d, lua,
>     ocaml, js, perl, objc,
>     cs, php, ruby, rust
>    
>     These languages may also work if the corresponding Sublime
>     syntax plugin is installed:
>     vb, typescript, elixir
>    
>     Be sure to run the "Reload language list from settings" command
>     after editing this setting
>    */
>    "languages": ["cpp", "python"],
>    }
>    
>    _User Settings_
>    
>    {
>    "HMAC": "Wqm9l1IEE5KD7AoxS3+HwA=="
>    }
>    
>    Thanks once again for looking into it.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/LuckyGeck/YcmdCompletion/issues/24#issuecomment-223752032,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAK4OHy-hyeABAc6hMm9sB2R_8Yh0NLPks5qIWm_gaJpZM4IuEuy
> .

## 

Pavel Sychev

**Comment by kaushikcfd** [comment]
Tried it. Does not work. Any other thing that I could try. It would be immensely helpful.

**Comment by LuckyGeck** [comment]
Maybe, try using default python (comment out python_binary_path param in your config).

**Comment by kaushikcfd** [comment]
Yup, great this worked. Almost there, does anyone know how to get completions from the included file. I mean say currently I have a file named `hello.cpp` and in the same directory I have `hello.hpp`. If I included `hello.hpp` in `hello.cpp` then according to `YCMD` I should be able to get completions from `hello.hpp`. But that does not happen in my case. I only get completions from the functions and classes declared within the current file. While using `YCMD` with `vim` and `atom` I do get auto-completions from the included files as well. Do you have any idea regarding this or if you could point me to something related to this. 

Thanks a lot.

**Comment by LuckyGeck** [comment]
It should work automatically, if you've added correct '-I' params in . ycm_extra_conf.py

**Comment by kaushikcfd** [comment]
Ok. So here's how it worked.
I re-installed `ycmd` by completely by fetching the `repo` and again did all the steps which were mentioned there. And removed `ST3` with all the packages and the `config` directories. And again installed the package. It's working fine now.
