### ISSUE TITLE
GoTo Definition via F12

### ISSUE THREAD

**Issue by cipri-tom** [LuckyGeck/YcmdCompletion#30]
Hi,

I managed to install everything and I think it's working. The feature that made me have this is "go to typedef". 

However, if I press F12 on a `myType_t`, nothing happens and the status bar indicates "Unable to find myType_t". But if I run "Ycmd: GoTo Definition" from the command palette, then it correctly goes to the definition.

Any idea why ? Can I set up Ycmd to work with F12 ?

Thank you!

**Comment by LuckyGeck** [comment]
Hi!

I think F12 uses internal Sublime's index but not the plugin's one. However, you can bind F12 to "Ycmd: GoTo Definition" command using Sublime's key bindings file.
